version: '3'

volumes:
  postgresql:
  postgresql_data:

services:
  db:
    image: postgres
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var
    environment:
      POSTGRES_DB: decolar
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
